/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer;

/**
 *
 * @author SR
 */
public class ComputerList extends javax.swing.JFrame {

    /**
     * Creates new form ComputerList
     */
    public ComputerList() {
        initComponents();
        this.setBounds(100,50,861,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logout2 = new javax.swing.JButton();
        review2 = new javax.swing.JButton();
        DeshBoard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddComputer1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SerialSearch = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        deshboard2 = new javax.swing.JMenuItem();
        LabPerformence = new javax.swing.JMenuItem();
        profile = new javax.swing.JMenuItem();
        review = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 90));
        jPanel2.setLayout(null);

        logout2.setText("Logout");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        jPanel2.add(logout2);
        logout2.setBounds(680, 20, 120, 40);

        review2.setText("Review");
        review2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review2ActionPerformed(evt);
            }
        });
        jPanel2.add(review2);
        review2.setBounds(470, 20, 120, 40);

        DeshBoard.setText("Deshboard");
        DeshBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshBoardActionPerformed(evt);
            }
        });
        jPanel2.add(DeshBoard);
        DeshBoard.setBounds(280, 20, 120, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S1101", "182.48.76.165", "Search For more"},
                {"S1102", "182.48.76.115", "Search For more"},
                {"S1103", "182.48.76.118", "Search For more"},
                {"S1104", "182.48.76.152", "Search For more"},
                {"S1105", "182.48.76.163", "Search For more"},
                {"S1106", "182.48.76.164", "Search For more"},
                {"S1107", "182.48.76.167", "Search For more"},
                {"S1108", "182.48.76.169", "Search For more"},
                {"S1109", "182.48.76.168", "Search For more"},
                {"S1110", "182.48.76.175", "Search For more"},
                {"S1111", "182.48.76.184", "Search For more"},
                {"S1112", "182.48.76.185", "Search For more"},
                {"S1113", "182.48.76.186", "Search For more"}
            },
            new String [] {
                "Serial No.", "IP Address", "Details"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 840, 300);

        AddComputer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddComputer1.setForeground(new java.awt.Color(0, 0, 204));
        AddComputer1.setText("ADD New Computer");
        AddComputer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddComputer1ActionPerformed(evt);
            }
        });
        getContentPane().add(AddComputer1);
        AddComputer1.setBounds(210, 610, 380, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Enter Serial No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 496, 200, 30);
        getContentPane().add(SerialSearch);
        SerialSearch.setBounds(190, 500, 310, 22);
        getContentPane().add(Message);
        Message.setBounds(220, 530, 540, 30);

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 0, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(320, 565, 240, 30);

        menu.setText("Menu");

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menu.add(home);

        deshboard2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        deshboard2.setText("DeshBoard");
        menu.add(deshboard2);

        LabPerformence.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        LabPerformence.setText("Lab Performence");
        LabPerformence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabPerformenceActionPerformed(evt);
            }
        });
        menu.add(LabPerformence);

        profile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        menu.add(profile);

        review.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        review.setText("Review");
        menu.add(review);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home HM= new Home();
        HM.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login L=new Login();
        L.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void DeshBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshBoardActionPerformed
        // TODO add your handling code here:
        DashBoard D = new DashBoard();
        D.setVisible(true);
    }//GEN-LAST:event_DeshBoardActionPerformed

    private void review2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review2ActionPerformed
        // TODO add your handling code here:
        Review R= new Review();
        R.setVisible(true);
    }//GEN-LAST:event_review2ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        Login L=new Login();
        L.setVisible(true);
    }//GEN-LAST:event_logout2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        ComputerDetails C=new ComputerDetails();
        C.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void AddComputer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddComputer1ActionPerformed
        // TODO add your handling code here:
        AddComputer AC= new AddComputer();
        AC.setVisible(true);
    }//GEN-LAST:event_AddComputer1ActionPerformed

    private void LabPerformenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabPerformenceActionPerformed
        // TODO add your handling code here:
        LabPerformance LP= new LabPerformance();
        LP.setVisible(true);
    }//GEN-LAST:event_LabPerformenceActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        Profile P= new Profile();
        P.setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddComputer1;
    private javax.swing.JButton DeshBoard;
    private javax.swing.JMenuItem LabPerformence;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField SerialSearch;
    private javax.swing.JMenuItem deshboard2;
    private javax.swing.JMenuItem home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton logout2;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenuItem review;
    private javax.swing.JButton review2;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
