/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer;

/**
 *
 * @author SR
 */
public class ComputerDetails extends javax.swing.JFrame {

    /**
     * Creates new form ComputerDetails
     */
    public ComputerDetails() {
        initComponents();
        this.setBounds(100,50,861,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SINO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SINO1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SINO2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SINO3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SINO4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SINO5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SINO6 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 90));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 100);

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(260, 650, 340, 40);

        jLabel1.setText("Serial No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 130, 70, 16);
        getContentPane().add(SINO);
        SINO.setBounds(120, 130, 570, 0);

        jLabel2.setText("IP Address:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 180, 70, 30);
        getContentPane().add(SINO1);
        SINO1.setBounds(120, 180, 570, 30);

        jLabel3.setText("Status:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 230, 70, 30);
        getContentPane().add(SINO2);
        SINO2.setBounds(120, 230, 570, 30);

        jLabel4.setText("Brand Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 300, 90, 30);
        getContentPane().add(SINO3);
        SINO3.setBounds(120, 300, 570, 30);

        jLabel5.setText("Configaretion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 360, 90, 30);
        getContentPane().add(SINO4);
        SINO4.setBounds(110, 360, 570, 30);

        jLabel6.setText("Last Service Date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 410, 110, 30);
        getContentPane().add(SINO5);
        SINO5.setBounds(130, 410, 550, 30);

        jLabel7.setText("Condition:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 460, 70, 30);
        getContentPane().add(SINO6);
        SINO6.setBounds(110, 460, 570, 30);

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(480, 540, 130, 40);

        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(51, 0, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(240, 540, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        ComputerList CL= new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        UpdateComputerInformation UCI= new UpdateComputerInformation();
        UCI.setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ComputerList CL= new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SINO;
    private javax.swing.JLabel SINO1;
    private javax.swing.JLabel SINO2;
    private javax.swing.JLabel SINO3;
    private javax.swing.JLabel SINO4;
    private javax.swing.JLabel SINO5;
    private javax.swing.JLabel SINO6;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
