/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer;

/**
 *
 * @author SR
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        this.setBounds(100,50,861,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        review6 = new javax.swing.JButton();
        computer5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        profile2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        see1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        see2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        computer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        see3 = new javax.swing.JButton();
        review2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        home3 = new javax.swing.JMenuItem();
        computer8 = new javax.swing.JMenuItem();
        LabPreformence = new javax.swing.JMenuItem();
        profile = new javax.swing.JMenuItem();
        review = new javax.swing.JMenuItem();
        logout8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 90));
        jPanel1.setLayout(null);

        logout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setText("Logut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(700, 20, 130, 50);

        review6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        review6.setForeground(new java.awt.Color(51, 102, 255));
        review6.setText("Review");
        review6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review6ActionPerformed(evt);
            }
        });
        jPanel1.add(review6);
        review6.setBounds(520, 20, 140, 40);

        computer5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        computer5.setForeground(new java.awt.Color(51, 102, 255));
        computer5.setText("Computer");
        computer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer5ActionPerformed(evt);
            }
        });
        jPanel1.add(computer5);
        computer5.setBounds(310, 20, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, -2, 860, 90);

        jPanel2.setLayout(null);

        profile2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profile2.setForeground(new java.awt.Color(0, 51, 255));
        profile2.setText("Profiles");
        profile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile2ActionPerformed(evt);
            }
        });
        jPanel2.add(profile2);
        profile2.setBounds(0, 0, 210, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 80, 90, 30);
        jPanel2.add(Name);
        Name.setBounds(100, 90, 180, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 140, 70, 22);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 140, 170, 0);

        see1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        see1.setForeground(new java.awt.Color(0, 102, 255));
        see1.setText("See More");
        see1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see1ActionPerformed(evt);
            }
        });
        jPanel2.add(see1);
        see1.setBounds(80, 220, 160, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Emaill:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 220, 70, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 410, 290);

        jPanel3.setLayout(null);

        see2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        see2.setForeground(new java.awt.Color(0, 102, 255));
        see2.setText("See More");
        see2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see2ActionPerformed(evt);
            }
        });
        jPanel3.add(see2);
        see2.setBounds(290, 135, 140, 20);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S1101", "182.48.76.165", "Active"},
                {"S1102", "182.48.76.115", "Active"},
                {"S1103", "182.48.76.118", "Active"},
                {"S1104", "182.76.45.158", null}
            },
            new String [] {
                "Serial No.", "IP Address", "Deatils"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 410, 120);

        computer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        computer.setForeground(new java.awt.Color(0, 0, 255));
        computer.setText("Computer");
        jPanel3.add(computer);
        computer.setBounds(70, 10, 250, 37);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(410, 90, 450, 290);

        jPanel4.setLayout(null);

        see3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        see3.setForeground(new java.awt.Color(51, 102, 255));
        see3.setText("See More");
        see3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see3ActionPerformed(evt);
            }
        });
        jPanel4.add(see3);
        see3.setBounds(630, 200, 210, 20);

        review2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        review2.setForeground(new java.awt.Color(0, 51, 255));
        review2.setText("Review");
        review2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                review2ActionPerformed(evt);
            }
        });
        jPanel4.add(review2);
        review2.setBounds(270, 10, 360, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/12/2019", "520014", "Sabbir", "Si. no. 1101 is good"},
                {"13/12/2019", "520018", "Antu", "si. no. 1105 have windows problem"},
                {"14/12/2019", "520085", "Imran", "si. no. 1108 is not starting"},
                {"15/12/2019", "520075", "Sujon", null}
            },
            new String [] {
                "Date", "ID", "Name", "Details"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(12, 120, 830, 120);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 380, 860, 370);

        home.setText("Menu");

        home3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        home3.setText("Home");
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });
        home.add(home3);

        computer8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        computer8.setText("Computer");
        computer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer8ActionPerformed(evt);
            }
        });
        home.add(computer8);

        LabPreformence.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        LabPreformence.setText("Lab Performence");
        LabPreformence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabPreformenceActionPerformed(evt);
            }
        });
        home.add(LabPreformence);

        profile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        home.add(profile);

        review.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        review.setText("Review");
        review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewActionPerformed(evt);
            }
        });
        home.add(review);

        logout8.setText("Logout");
        logout8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout8ActionPerformed(evt);
            }
        });
        home.add(logout8);

        jMenuBar1.add(home);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer8ActionPerformed
        ComputerList CL= new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_computer8ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login LG= new Login();
        LG.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void computer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer5ActionPerformed
        ComputerList CL= new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_computer5ActionPerformed

    private void see3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see3ActionPerformed
        Review R= new Review();
        R.setVisible(true);
    }//GEN-LAST:event_see3ActionPerformed

    private void see2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see2ActionPerformed
        ComputerList CL= new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_see2ActionPerformed

    private void see1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see1ActionPerformed
        Profile P= new Profile();
        P.setVisible(true);
    }//GEN-LAST:event_see1ActionPerformed

    private void profile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile2ActionPerformed
        Profile P= new Profile();
        P.setVisible(true);
    }//GEN-LAST:event_profile2ActionPerformed

    private void review2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review2ActionPerformed
        Review R= new Review();
        R.setVisible(true);
    }//GEN-LAST:event_review2ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        Home H= new Home();
        H.setVisible(true);
    }//GEN-LAST:event_home3ActionPerformed

    private void LabPreformenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabPreformenceActionPerformed
        LabPerformance LP= new LabPerformance();
        LP.setVisible(true);
    }//GEN-LAST:event_LabPreformenceActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        Profile P= new Profile();
        P.setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
        Review R= new Review();
        R.setVisible(true);
                
    }//GEN-LAST:event_reviewActionPerformed

    private void logout8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout8ActionPerformed
        Login L= new Login();
        L.setVisible(true);
    }//GEN-LAST:event_logout8ActionPerformed

    private void review6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_review6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_review6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LabPreformence;
    private javax.swing.JLabel Name;
    private javax.swing.JButton computer;
    private javax.swing.JButton computer5;
    private javax.swing.JMenuItem computer8;
    private javax.swing.JMenu home;
    private javax.swing.JMenuItem home3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logout;
    private javax.swing.JMenuItem logout8;
    private javax.swing.JMenuItem profile;
    private javax.swing.JButton profile2;
    private javax.swing.JMenuItem review;
    private javax.swing.JButton review2;
    private javax.swing.JButton review6;
    private javax.swing.JButton see1;
    private javax.swing.JButton see2;
    private javax.swing.JButton see3;
    // End of variables declaration//GEN-END:variables
}
