/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SR
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Registration() {
        initComponents();
        this.setBounds(100,50,861,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        Cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Lohin = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        I = new javax.swing.JLabel();
        I1 = new javax.swing.JLabel();
        I2 = new javax.swing.JLabel();
        I3 = new javax.swing.JLabel();
        I4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home2 = new javax.swing.JMenuItem();
        login2 = new javax.swing.JMenuItem();
        registration = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Registration Here.....");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 90, 530, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Create a free account on divice and get started");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 540, 40);

        jLabel3.setText("Enter Your ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 260, 90, 30);

        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1);
        T1.setBounds(210, 270, 200, 22);

        jLabel4.setText("Enter Your Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 320, 110, 30);

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2);
        T2.setBounds(210, 330, 200, 22);

        jLabel5.setText("Enter Your Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 380, 120, 30);

        T3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3ActionPerformed(evt);
            }
        });
        getContentPane().add(T3);
        T3.setBounds(210, 390, 200, 22);

        jLabel6.setText("Create a password:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 450, 130, 30);

        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4);
        T4.setBounds(210, 460, 200, 22);

        jLabel7.setText("Re-type your password ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 530, 150, 30);

        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });
        getContentPane().add(T5);
        T5.setBounds(210, 530, 200, 22);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(0, 0, 255));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(580, 640, 120, 40);

        jRadioButton1.setText("I have accept the term and condition");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(250, 580, 280, 25);

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(0, 51, 255));
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(40, 650, 120, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        Lohin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lohin.setForeground(new java.awt.Color(255, 51, 51));
        Lohin.setText("Login");
        Lohin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LohinActionPerformed(evt);
            }
        });
        jPanel1.add(Lohin);
        Lohin.setBounds(689, 15, 120, 40);

        Home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 0, 51));
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(280, 15, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 90);

        I.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(I);
        I.setBounds(210, 560, 480, 20);

        I1.setForeground(new java.awt.Color(255, 51, 102));
        getContentPane().add(I1);
        I1.setBounds(220, 300, 420, 20);

        I2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(I2);
        I2.setBounds(210, 360, 420, 20);

        I3.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(I3);
        I3.setBounds(210, 430, 440, 20);

        I4.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(I4);
        I4.setBounds(210, 490, 490, 20);

        jMenu1.setText("Menu");

        home2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        home2.setText("Home");
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        jMenu1.add(home2);

        login2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        login2.setText("Login");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });
        jMenu1.add(login2);

        registration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        registration.setText("Registration");
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        jMenu1.add(registration);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void T3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T3ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        Login LG= new Login();
       LG.setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home HM= new Home();
       HM.setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    private void LohinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LohinActionPerformed
        Login LG= new Login();
       LG.setVisible(true);
    }//GEN-LAST:event_LohinActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
            try { 
           
                //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/computer lab","root","");
                String sql= "INSERT into user2"+"(ID,Name,Email,Password)"+"values(?,?,?,?)"; 
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1,T1.getText());
                pst.setString(2,T2.getText());
                pst.setString(3,T3.getText());
                pst.setString(4,T5.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted Successfully");
            } catch (SQLException |HeadlessException ex) {
            Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE, null, ex);
             
            }
            Login LG= new Login();
            LG.setVisible(true);
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        Home H= new Home();
        H.setVisible(true);
    }//GEN-LAST:event_home2ActionPerformed

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        Registration H= new Registration();
        H.setVisible(true);
    }//GEN-LAST:event_registrationActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        Login L= new Login();
        L.setVisible(true);
    }//GEN-LAST:event_login2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Home;
    private javax.swing.JLabel I;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JButton Lohin;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JMenuItem home2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenuItem login2;
    private javax.swing.JMenuItem registration;
    // End of variables declaration//GEN-END:variables

    private static class loginPage {

        public loginPage() {
        }
    }
}
