/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer;

/**
 *
 * @author SR
 */
public class UpdateComputerInformation extends javax.swing.JFrame {

    /**
     * Creates new form UpdateComputerInformation
     */
    public UpdateComputerInformation() {
        initComponents();
        this.setBounds(100,50,861,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SINO1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SINO2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SINO3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SINO4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SINO5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SINO6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SINO7 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 90));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 100);

        jLabel1.setText("Update Serial No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 110, 16);
        getContentPane().add(SINO1);
        SINO1.setBounds(130, 130, 570, 30);

        jLabel2.setText("Update IP Address:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 110, 30);
        getContentPane().add(SINO2);
        SINO2.setBounds(140, 180, 570, 30);

        jLabel3.setText("Update Status:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 230, 100, 30);
        getContentPane().add(SINO3);
        SINO3.setBounds(130, 230, 570, 30);

        jLabel4.setText("Update Brand Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 300, 120, 30);
        getContentPane().add(SINO4);
        SINO4.setBounds(140, 300, 680, 30);

        jLabel5.setText("Update Configaretion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 360, 130, 30);
        getContentPane().add(SINO5);
        SINO5.setBounds(150, 360, 690, 30);

        jLabel6.setText("Update Service Date:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 410, 130, 30);
        getContentPane().add(SINO6);
        SINO6.setBounds(140, 410, 570, 30);

        jLabel7.setText("Condition Condition:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 460, 120, 30);
        getContentPane().add(SINO7);
        SINO7.setBounds(140, 460, 540, 30);

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(480, 640, 160, 31);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(51, 0, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(259, 640, 170, 31);

        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 640, 170, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ComputerDetails CD= new ComputerDetails();
        CD.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        ComputerList CL=new ComputerList();
        CL.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        ComputerDetails CD= new ComputerDetails();
        CD.setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateComputerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateComputerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateComputerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateComputerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateComputerInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SINO1;
    private javax.swing.JLabel SINO2;
    private javax.swing.JLabel SINO3;
    private javax.swing.JLabel SINO4;
    private javax.swing.JLabel SINO5;
    private javax.swing.JLabel SINO6;
    private javax.swing.JLabel SINO7;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
